name: xadamonad
version: 1.0.0
synopsis: "Adam Flott's xmonad config"
description: "Adam Flott's xmonad config"
maintainer: Adam Flott <adam@adamflott.com>
license: MIT
github: adamflott/xadamonad
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadFailDesugaring
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

executables:
  xmonad:
    main: xmonad.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -O2
    source-dirs: .
    dependencies:
      - base
      - containers
      - data-default
      - dbus
      - xmonad
      - xmonad-contrib
      - xmonad-extras
      - xmonad-wallpaper
      - taffybar
      - utf8-string >= 1.0

  taffybar:
    main: taffybar.hs
    source-dirs: .
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base
      - containers
      - directory
      - filepath
      - gtk3
      - gtk-traymanager>=0.1.6
      - taffybar
      - xmonad-contrib>=0.13
      - X11>=1.8
