name: xadamonad
version: 1.0.0
synopsis: "Adam Flott's xmonad config"
description: "Adam Flott's xmonad config"
maintainer: Adam Flott <adam@adamflott.com>
license: MIT
github: adamflott/xadamonad
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wredundant-constraints

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base
  - containers
  - data-default
  - dbus
  - xmonad>=0.15
  - xmonad-contrib
  - xmonad-extras
  - xmonad-wallpaper
  - xmobar

executables:
  xmonad:
    main: xmonad.hs
    source-dirs: .
