name: xadamonad
version: 1.0.0
synopsis: "Adam Flott's xmonad config"
description: "Adam Flott's xmonad config"
maintainer: Adam Flott <adam@adamflott.com>
license: MIT
github: adamflott/xadamonad
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options:
  - -Wall
  - -O
  - -fwarn-unused-imports
  - -fhide-source-paths
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wredundant-constraints
  - -Wpartial-fields
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wmissing-deriving-strategies
  - -Wmissing-export-lists
  - -funbox-strict-fields
#  - -Werror

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTSyntax
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoMonomorphismRestriction
  - NoImplicitPrelude
  - NumDecimals
  - NumericUnderscores
  - OverloadedStrings
  - ParallelListComp
  - PatternGuards
  - PatternSynonyms
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - StaticPointers
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeInType
  - TypeOperators
  - TypeSynonymInstances
  - UnicodeSyntax
  - ViewPatterns

dependencies:
  - base
  - containers
  - data-default
  - dbus
  - hostname
  - xmonad >= 0.17
  - xmonad-contrib >= 0.17
  - xmonad-extras >= 0.17
  - xmonad-wallpaper
  - relude >= 1.0.0.1

executables:
  xmonad:
    main: xmonad.hs
    source-dirs: .
