resolver: nightly-2020-01-17
#resolver: lts-13.3

packages:
- '.'
- './xmonad-wallpaper-0.0.1.4'

extra-deps:
- xmobar-0.32
- iwlib-0.1.0@sha256:226e4582d6878166a172ff98c868e25c4ed478ab28ab493498e464b1fe19d39a,921
- magic-1.1@sha256:3a31ca1c49fa5f6a857f647471739bd240a6020af6ae43e71fb72201fc482fa2,928

flags:
  xmobar:
    all_extensions: true

extra-package-dbs: []

nix:
  enable: true
  packages:
  - file
  - wirelesstools
  - alsaLib.dev
  - zlib
  - xorg.libX11
  - xorg.libXrandr
  - xorg.libXScrnSaver
  - pkg-config
  - xorg.libXext
  - xorg.libXft
  - xorg.libXpm
