#resolver: nightly-2022-07-11
resolver: lts-20.3

packages:
- '.'
- './xmonad-wallpaper-0.0.1.5'

extra-deps: []

extra-package-dbs: []

nix:
  enable: true
  packages:
  - file
  - wirelesstools
  - alsaLib.dev
  - zlib
  - xorg.libX11
  - xorg.libXrandr
  - xorg.libXScrnSaver
  - pkg-config
  - xorg.libXext
  - xorg.libXft
  - xorg.libXpm
